version: '3.9'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - miniodata:/data
    ports:
      - "9000:9000"       # S3 API
      - "9001:9001"       # Console UI
    command: server /data --console-address ":9001"

  user-service:
    build:
      context: ./user_service
    env_file:
      - ./user_service/.env
    depends_on:
      - postgres
    ports:
      - "8001:8000"
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  school-service:
    build:
      context: ./school_service
    env_file:
      - ./school_service/.env
    depends_on:
      - postgres
    ports:
      - "8002:8000"
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  enrollment-service:
    build:
      context: ./enrollment_service
    env_file:
      - ./enrollment_service/.env
    depends_on:
      - postgres
    ports:
      - "8003:8000"
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  attendance-service:
    build:
      context: ./attendance_service
    env_file:
      - ./attendance_service/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8004:8000"
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  assessment-service:
    build:
      context: ./assessment_service
    env_file:
      - ./assessment_service/.env
    depends_on:
      - postgres
    ports:
      - "8005:8000"
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  lms-service:
    build:
      context: ./lms_service
    env_file:
      - ./lms_service/.env
    ports:
      - "8006:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  communication-service:
    build:
      context: ./communication_service
    env_file:
      - ./communication_service/.env
    depends_on:
      - redis
    ports:
      - "8007:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  notification-service:
    build:
      context: ./notification_service
    env_file:
      - ./notification_service/.env
    depends_on:
      - redis
    ports:
      - "8008:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  analytics-service:
    build:
      context: ./analytics_service
    env_file:
      - ./analytics_service/.env
    depends_on:
      - postgres
    ports:
      - "8009:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  content-service:
    build:
      context: ./content_service
    env_file:
      - ./content_service/.env
    depends_on:
      - minio
    ports:
      - "8010:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata:
  mongodata:
  miniodata:

