"""Initial schema

Revision ID: 2c029454bf1b
Revises: 
Create Date: 2025-05-29 18:15:18.952194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c029454bf1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', name='termstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('curriculum', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('assigned_teacher_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('reason_for_exit', sa.String(), nullable=True),
    sa.Column('transferred_from_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transferred_from_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_table('sections')
    op.drop_table('grades')
    op.drop_table('academic_terms')
    # ### end Alembic commands ###
