"""Initial analytic schema

Revision ID: 7b56dfc4348f
Revises: 
Create Date: 2025-05-31 19:12:35.066596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b56dfc4348f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytic_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytic_metrics_id'), 'analytic_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_analytic_metrics_student_id'), 'analytic_metrics', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytic_metrics_student_id'), table_name='analytic_metrics')
    op.drop_index(op.f('ix_analytic_metrics_id'), table_name='analytic_metrics')
    op.drop_table('analytic_metrics')
    # ### end Alembic commands ###
